name: CI
on:
  pull_request:
    branches: [ main, release/**, hotfix/** ]
  push:
    branches: [ main ]

jobs:
  build:
    name: Lint • Build • Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install web-ext
        run: npm i -g web-ext

      - name: Lint (web-ext)
        run: |
          web-ext lint -s src --verbose || true
          # If you want the lint to be blocking, remove the `|| true`

      - name: Package MV2 zip
        run: |
          mkdir -p dist
          # pack whatever files you ship; adjust path if you keep sources in root
          (cd src && zip -r ../dist/CrunchyQueue-${{ github.sha }}.zip .)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: crunchyqueue-${{ github.sha }}
          path: dist/*.zip
          if-no-files-found: error
