name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # to create release & upload assets

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install web-ext
        run: npm i -g web-ext

      - name: Build release zip
        run: |
          mkdir -p dist
          (cd src && zip -r ../dist/CrunchyQueue-${{ github.ref_name }}.zip .)

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: CrunchyQueue ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-beta') || contains(github.ref_name, '-rc') }}
          files: dist/*.zip
